### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Diamondtroller** [abrasic/blendpresence#5]
Tried installing it, but fails.
Blender version:
```
Blender 3.0.0
        build date: 2021-12-17
        build time: 06:39:03
        build commit date: 2021-12-02
        build commit time: 18:35
        build hash: f1cca3055776
        build platform: Linux
        build type: Release
```
Linux version:
`5.16.2-1-MANJARO`
Traceback:
```
Traceback (most recent call last):
  File "/usr/share/blender/3.0/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
  File "/home/dt/.config/blender/3.0/scripts/addons/blendpresence/__init__.py", line 582, in register
    bpi.connected = connectRPC()
  File "/home/dt/.config/blender/3.0/scripts/addons/blendpresence/__init__.py", line 16, in connectRPC
    rpcClient.connect()
  File "/home/dt/.config/blender/3.0/scripts/addons/blendpresence/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/dt/.config/blender/3.0/scripts/addons/blendpresence/pypresence/baseclient.py", line 128, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.10/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
TypeError: _UnixSelectorEventLoop.create_unix_connection() got an unexpected keyword argument 'loop'
```

**Comment by abrasic** [comment]
Hi there, thanks for your report.

This appears to primarily be a pypresence issue, but try the following as a temporary fix:
- If necessary, remove the addon from Blender and close the application.
- Go to line 128 of `pypresence/baseclient.py`
- Remove the `loop=self.loop` argument. Save the file. Restart blender.

I'll be sure to apply this fix after some testing, but let me know if the fix above worked for you.

Cheers

**Comment by Diamondtroller** [comment]
Yeah, thank you.
The fix solved the issue and presence works now.

**Comment by abrasic** [comment]
Closing for [1.7.1](https://github.com/abrasic/blendpresence/releases/tag/1.7.1). If the issue persists on that version please let me know
