### ISSUE TITLE
Addon producing error when enabled.

### ISSUE THREAD

**Issue by inkoalawetrust** [abrasic/blendpresence#7]
Every time I try to enable the addon I get this error:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\inkoalawetrust\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendpresence\__init__.py", line 30, in <module>
    class bpi:
  File "C:\Users\inkoalawetrust\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendpresence\__init__.py", line 36, in bpi
    blendGPU = gpu.platform.renderer_get()
AttributeError: module 'gpu' has no attribute 'platform'
```

This is pretty much all I get when I try turning the addon on. So I don't have any other information to add. Besides that it doesn't seem to like something about my GPU.

**Comment by abrasic** [comment]
Hi, thanks for your report.

This error happens because the gpu.platform module (which is required to display the GPU name for a display option) does not exist in Blender 2.93. I can attempt a way to circumvent this problem in a future release but for now you can instead downgrade to 1.6.0 as a temporary fix.

Cheers

**Comment by abrasic** [comment]
Closing for [1.7.1](https://github.com/abrasic/blendpresence/releases/tag/1.7.1). If the issue persists on that version please let me know
